# Generated by Django 2.1.1 on 2018-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kick_of_Time', models.CharField(max_length=100)),
                ('home_Team', models.CharField(max_length=100)),
                ('home_Percent', models.CharField(max_length=100)),
                ('home_Odd', models.CharField(max_length=100)),
                ('draw_Odd', models.CharField(max_length=100)),
                ('away_Odd', models.CharField(max_length=100)),
                ('away_Team', models.CharField(max_length=100)),
                ('away_Percent', models.CharField(max_length=100)),
                ('prediction', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Best Tips',
                'ordering': ['kick_of_Time', 'home_Odd'],
            },
        ),
    ]
