# Generated by Django 2.1.1 on 2018-09-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='besttips',
            options={'verbose_name_plural': 'Best Tips'},
        ),
    ]
