# Generated by Django 2.1.1 on 2018-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180927_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurFavouritePick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kick_of_Time', models.CharField(max_length=100)),
                ('home_Team', models.CharField(max_length=100)),
                ('away_Team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('win_Percent', models.CharField(max_length=100)),
                ('win_Odd', models.CharField(max_length=100)),
                ('our_Pick', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Best Tips',
            },
        ),
    ]
