# Generated by Django 2.1.1 on 2018-10-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ourfavouritepick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourfavouritepick',
            options={'verbose_name_plural': 'Our Favourite Picks'},
        ),
    ]
