# Generated by Django 2.0.6 on 2018-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181018_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourfavouritepick',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
